-- AlterTable
ALTER TABLE `Activity` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Booking` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `BookingEntry` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Destination` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Hotel` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `HotelLocation` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Trip` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `TripLeg` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `User` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `deletedAt` DATETIME(3);

-- AlterTable
ALTER TABLE `Venue` ADD COLUMN     `createdAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN     `updatedAt` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);
